import type { FormatDefinition } from '../types/format';

/**
 * A handful of ready-to-use formats shipped with the extension. They double as
 * worked examples for the format-definition schema. Users can duplicate any of
 * these into their global/workspace store and edit freely.
 */
export const BUILTIN_FORMATS: FormatDefinition[] = [
  {
    name: 'Nested Firmware (example)',
    description:
      'Demonstrates nested structures — a Header and an ImageInfo container with ' +
      'child offsets relative to their parent, plus a flat Checksum field.',
    version: '1.0.0',
    fileExtensions: ['.fw'],
    endianness: 'little',
    magic: { offset: 0, bytes: '46 57 01 00' },
    fields: [
      {
        name: 'Header',
        offset: 0,
        fields: [
          { name: 'Magic', type: 'uint32', offset: 0, display: 'hex', description: 'Firmware magic value' },
          { name: 'Version', type: 'uint16', offset: 4 },
          {
            name: 'Flags',
            type: 'uint16',
            offset: 6,
            fields: [
              { name: 'Compressed', bits: '0' },
              { name: 'Signed', bits: '1' },
              { name: 'Stage', bits: '4-6', enum: { '0': 'boot', '1': 'app', '2': 'recovery' } },
            ],
          },
        ],
      },
      {
        name: 'ImageInfo',
        offset: 8,
        fields: [
          { name: 'ImageSize', type: 'uint32', offset: 0, display: 'dec', unit: 'bytes' },
          { name: 'LoadAddress', type: 'uint32', offset: 4, display: 'hex' },
          { name: 'EntryPoint', type: 'uint32', offset: 8, display: 'hex' },
        ],
      },
      { name: 'Checksum', type: 'uint32', offset: 20, display: 'hex' },
    ],
  },
  {
    name: 'Firmware Image (example)',
    description:
      'The sample firmware header from the Binary Viewer documentation. Magic "FW\\x01\\x00".',
    version: '1.0.0',
    fileExtensions: ['.fw', '.img'],
    endianness: 'little',
    magic: { offset: 0, bytes: '46 57 01 00' },
    fields: [
      { name: 'Magic', type: 'ascii', offset: 0, length: 2, description: 'ASCII "FW"' },
      { name: 'Format Version', type: 'uint16', offset: 2 },
      { name: 'Version', type: 'uint16', offset: 4, description: 'Firmware version' },
      {
        name: 'Flags',
        type: 'flags',
        offset: 6,
        size: 2,
        fields: [
          { name: 'Compressed', bits: '0' },
          { name: 'Signed', bits: '1' },
          { name: 'Encrypted', bits: '2' },
          { name: 'Stage', bits: '4-6', enum: { '0': 'boot', '1': 'app', '2': 'recovery' } },
          { name: 'Reserved', bits: '7-15' },
        ],
      },
      { name: 'Image Size', type: 'uint32', offset: 8, description: 'Payload size in bytes', display: 'dec' },
      { name: 'Load Address', type: 'uint32', offset: 12, display: 'hex' },
      {
        name: 'Build Timestamp',
        type: 'timestamp',
        offset: 16,
        timestamp: { size: 4, unit: 's', epoch: 'unix' },
      },
      { name: 'CRC32', type: 'uint32', offset: 20, display: 'hex' },
      { name: 'Product', type: 'ascii', offset: 24, length: 16 },
    ],
  },
  {
    name: 'ELF Header',
    description: 'ELF32/ELF64 file header (first 64 bytes).',
    fileExtensions: ['.elf', '.o', '.so', '.axf'],
    endianness: 'little',
    magic: { offset: 0, bytes: '7F 45 4C 46' },
    fields: [
      { name: 'EI_MAG', type: 'bytes', offset: 0, size: 4, description: '0x7F "ELF"' },
      {
        name: 'EI_CLASS',
        type: 'enum',
        offset: 4,
        size: 1,
        enum: { '0': 'ELFCLASSNONE', '1': 'ELF32', '2': 'ELF64' },
      },
      {
        name: 'EI_DATA',
        type: 'enum',
        offset: 5,
        size: 1,
        enum: { '1': 'little-endian', '2': 'big-endian' },
      },
      { name: 'EI_VERSION', type: 'uint8', offset: 6 },
      {
        name: 'EI_OSABI',
        type: 'enum',
        offset: 7,
        size: 1,
        enum: { '0': 'System V', '3': 'Linux', '9': 'FreeBSD', '255': 'Standalone' },
      },
      { name: 'EI_PAD', type: 'bytes', offset: 8, size: 8 },
      {
        name: 'e_type',
        type: 'enum',
        offset: 16,
        size: 2,
        enum: { '0': 'NONE', '1': 'REL', '2': 'EXEC', '3': 'DYN', '4': 'CORE' },
      },
      {
        name: 'e_machine',
        type: 'enum',
        offset: 18,
        size: 2,
        enum: { '3': 'x86', '40': 'ARM', '62': 'x86-64', '183': 'AArch64', '243': 'RISC-V' },
      },
      { name: 'e_version', type: 'uint32', offset: 20 },
      { name: 'e_entry', type: 'uint64', offset: 24, display: 'hex' },
      { name: 'e_phoff', type: 'uint64', offset: 32, display: 'dec' },
      { name: 'e_shoff', type: 'uint64', offset: 40, display: 'dec' },
      { name: 'e_flags', type: 'uint32', offset: 48, display: 'hex' },
      { name: 'e_ehsize', type: 'uint16', offset: 52 },
      { name: 'e_phentsize', type: 'uint16', offset: 54 },
      { name: 'e_phnum', type: 'uint16', offset: 56 },
      { name: 'e_shentsize', type: 'uint16', offset: 58 },
      { name: 'e_shnum', type: 'uint16', offset: 60 },
      { name: 'e_shstrndx', type: 'uint16', offset: 62 },
    ],
  },
  {
    name: 'PNG Header',
    description: 'PNG signature and the IHDR chunk.',
    fileExtensions: ['.png'],
    endianness: 'big',
    magic: { offset: 0, bytes: '89 50 4E 47 0D 0A 1A 0A' },
    fields: [
      { name: 'Signature', type: 'bytes', offset: 0, size: 8 },
      { name: 'IHDR Length', type: 'uint32', offset: 8 },
      { name: 'IHDR Type', type: 'ascii', offset: 12, length: 4 },
      { name: 'Width', type: 'uint32', offset: 16 },
      { name: 'Height', type: 'uint32', offset: 20 },
      { name: 'Bit Depth', type: 'uint8', offset: 24 },
      {
        name: 'Color Type',
        type: 'enum',
        offset: 25,
        size: 1,
        enum: { '0': 'Grayscale', '2': 'RGB', '3': 'Palette', '4': 'Grayscale+A', '6': 'RGBA' },
      },
      { name: 'Compression', type: 'uint8', offset: 26 },
      { name: 'Filter', type: 'uint8', offset: 27 },
      { name: 'Interlace', type: 'enum', offset: 28, size: 1, enum: { '0': 'none', '1': 'Adam7' } },
    ],
  },
  {
    name: 'BMP Header',
    description: 'Windows BITMAPFILEHEADER + BITMAPINFOHEADER.',
    fileExtensions: ['.bmp', '.dib'],
    endianness: 'little',
    magic: { offset: 0, bytes: '42 4D' },
    fields: [
      { name: 'Signature', type: 'ascii', offset: 0, length: 2 },
      { name: 'File Size', type: 'uint32', offset: 2, display: 'dec' },
      { name: 'Reserved1', type: 'uint16', offset: 6 },
      { name: 'Reserved2', type: 'uint16', offset: 8 },
      { name: 'Pixel Data Offset', type: 'uint32', offset: 10, display: 'hex' },
      { name: 'DIB Header Size', type: 'uint32', offset: 14 },
      { name: 'Width', type: 'int32', offset: 18 },
      { name: 'Height', type: 'int32', offset: 22 },
      { name: 'Planes', type: 'uint16', offset: 26 },
      { name: 'Bits Per Pixel', type: 'uint16', offset: 28 },
      { name: 'Compression', type: 'uint32', offset: 30 },
      { name: 'Image Size', type: 'uint32', offset: 34 },
    ],
  },
];
